version: '2'
services:
  guestbook:
    image: gcr.io/google_containers/guestbook:v3
    ports:
      - "3000:3000"
    depends_on:
      - redis-master
      - redis-slave
  redis-master:
    image: redis:2.8.23
    ports:
      - "6379"
  redis-slave:
    image: kubernetes/redis-slave:v2
    ports:
      - "6379"
